-- 删除所有表以重新开始（谨慎使用！）
DROP TABLE IF EXISTS "imageEdits" CASCADE;
DROP TABLE IF EXISTS "imageGenerations" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "accounts" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- 删除枚举类型
DROP TYPE IF EXISTS "status" CASCADE;
DROP TYPE IF EXISTS "role" CASCADE;
